#!/usr/bin/env bash
set -u

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MANIFEST="$ROOT/src-tauri/Cargo.toml"
LOG="${TMPDIR:-/tmp}/ai-os-gm2-final-provider.log"

cd "$ROOT" || exit 1

fail() {
  echo "✗ $1"
  tail -160 "$LOG" 2>/dev/null || true
  echo "FAIL GM-2 Final Provider Integration: $1"
  exit 1
}

echo "GM-2 Final Provider Integration"

cargo test \
  --manifest-path "$MANIFEST" \
  generative_media::comfyui_provider::tests:: \
  --lib >"$LOG" 2>&1 ||
  fail "opaque local asset contract"

echo "✓ opaque normalized local asset contract"

cargo test \
  --manifest-path "$MANIFEST" \
  generative_media::comfyui_macos::gm2_final_readiness_tests:: \
  --lib >"$LOG" 2>&1 ||
  fail "durable Ready evidence contract"

echo "✓ stale profile/hash/runtime evidence cannot satisfy Ready"

cargo test \
  --manifest-path "$MANIFEST" \
  generative_media::registry::tests:: \
  --lib >"$LOG" 2>&1 ||
  fail "provider registry regression"

echo "✓ provider registry regression"

cargo test \
  --manifest-path "$MANIFEST" \
  generative_media::router::tests:: \
  --lib >"$LOG" 2>&1 ||
  fail "Local First routing regression"

echo "✓ Local First / manual exact-provider routing"
echo "✓ no provider switching after policy/execution failure"

cargo test \
  --manifest-path "$MANIFEST" \
  runtime::plan_runtime_bridge::tests::unconfirmed_generative_media_is_rejected_before_runtime_execution \
  --lib -- --exact >"$LOG" 2>&1 ||
  fail "Runtime media confirmation boundary"

echo "✓ Runtime confirmation still occurs before media execution"

cargo test \
  --manifest-path "$MANIFEST" \
  runtime::executor::gm2_final_provider_integration_tests::runtime_media_text_to_image_reaches_production_comfyui_real_e2e \
  --lib -- --ignored --exact --nocapture >"$LOG" 2>&1 ||
  fail "real production media.text-to-image path"

cat "$LOG"

grep -q 'LIVE_GM2_FINAL provider=comfyui' "$LOG" ||
  fail "real provider identity evidence"

grep -Eq 'mime=image/(png|jpeg|webp)' "$LOG" ||
  fail "real normalized MIME evidence"

grep -q 'handle=asset://generative-media/' "$LOG" ||
  fail "real opaque asset handle evidence"

grep -q 'ready=true' "$LOG" ||
  fail "real Ready production evidence"

echo "✓ Runtime canonical request"
echo "✓ production MediaProviderRegistry"
echo "✓ MediaRouter"
echo "✓ ComfyUI MediaProvider"
echo "✓ real /prompt -> history -> /view generation"
echo "✓ generated bytes persisted in AI-OS asset storage"
echo "✓ normalized MediaResult"

bash verify/rustfmt_changed.sh >"$LOG" 2>&1 ||
  fail "changed Rust formatting"

echo "✓ changed Rust formatting"

git diff --check >"$LOG" 2>&1 ||
  fail "git diff --check"

echo "✓ git diff --check"

echo "PASS GM-2 Final Provider Integration"
