pub(crate) mod cloud_provider;
pub(crate) mod comfyui;
pub(crate) mod comfyui_execution;
#[cfg(target_os = "macos")]
pub(crate) mod comfyui_macos;
pub(crate) mod comfyui_profile;
pub(crate) mod comfyui_provider;
pub(crate) mod comfyui_reference;
pub(crate) mod comfyui_reference_setup;
pub(crate) mod comfyui_setup;
pub(crate) mod domain;
pub(crate) mod executor;
pub(crate) mod model_advisor;
pub(crate) mod prompt_intelligence;
pub(crate) mod provider;
pub(crate) mod quality_loop;
pub(crate) mod reference_analysis;
pub(crate) mod registry;
pub(crate) mod router;
